apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: prod
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        location /dummy {
            default_type text/plain;  # Define el tipo de contenido como texto plano
            return 200 "Hello from Dummy App!";
        }

        location / {
            return 404;
        }
    }