apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: prod
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        location /dummy {
            default_type text/plain;  # Define el tipo de contenido como texto plano
            set $pod_ip "$POD_IP";
            set $pod_name "$POD_NAME";
            set $node_name "$NODE_NAME";
            return 200 "Hello from Dummy App!\nPod IP: $pod_ip\nPod Name: $pod_name\nNode Name: $node_name\n";
        }

        location / {
            return 404;
        }
    }