apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
  namespace: prod  # Namespace donde se desplegará la aplicación
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80