apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
      - name: podinfo
        image: francotel/pod-info:v1
        ports:
        - containerPort: 80
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName