apiVersion: v1
kind: Service
metadata:
  name: dummy-service
  namespace: prod  # Namespace donde se desplegará la aplicación
spec:
  selector:
    app: dummy-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP